import type { NewsItem, Opportunity, DailyReport, UserPreferences, AgentStats } from './types';

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: 'news_01',
    title: 'Anthropic Launches Claude 3.7 Sonnet with Hybrid Reasoning Mode',
    description: 'Anthropic has unveiled Claude 3.7 Sonnet, introducing hybrid reasoning where the model dynamically decides when to think deeply vs reply instantly.',
    content: 'Anthropic announced Claude 3.7 Sonnet, the industry’s first hybrid reasoning model capable of standard instantaneous responses as well as extended, self-guided thinking tokens. In developer coding benchmarks, it sets state-of-the-art results across SWE-bench Verified and competitive coding benchmarks.',
    url: 'https://www.anthropic.com/news/claude-3-7-sonnet',
    image_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    source_name: 'Anthropic News',
    category: 'ai',
    tags: ['Claude', 'LLM', 'Reasoning', 'Coding', 'Anthropic'],
    read_time_minutes: 4,
    summary: {
      what: 'Anthropic released Claude 3.7 Sonnet, featuring dynamic hybrid reasoning and record-setting developer coding capabilities.',
      why: 'Offers unmatched code generation and debugging accuracy, with developer API pricing remaining identical to 3.5 Sonnet.',
      action: 'Test Claude 3.7 via the Anthropic Console or Free Claude.ai web tier to upgrade your pair-programming workflow.',
      key_points: [
        'Hybrid reasoning allows switching between instantaneous answers and deep chain-of-thought tokens',
        'Scores 70.3% on SWE-bench Verified, surpassing previous top models',
        'Developer API pricing remains unchanged at $3/million input tokens'
      ]
    },
    importance_score: 96,
    relevance_score: 98,
    is_featured: true,
    is_trending: true,
    published_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'news_02',
    title: 'GitHub Releases Copilot Free for All Visual Studio Code Users',
    description: 'GitHub has removed the subscription requirement for VS Code developers, making basic AI completions and chat free permanently.',
    content: 'GitHub announced that starting today, every developer using Visual Studio Code can access GitHub Copilot for free without requiring a credit card or paid subscription. The free tier includes up to 2,000 code completions per month and 50 chat messages powered by Claude 3.5 Sonnet and GPT-4o.',
    url: 'https://github.blog/news-insights/product-news/github-copilot-free/',
    image_url: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=1200&q=80',
    source_name: 'GitHub Blog',
    category: 'development',
    tags: ['GitHub', 'Copilot', 'VSCode', 'Free Tier', 'AI Tools'],
    read_time_minutes: 3,
    summary: {
      what: 'GitHub made Copilot free for all VS Code developers without requiring a payment method.',
      why: 'Lowers the barrier to entry for students and developers to use state-of-the-art AI code completion directly in their IDE.',
      action: 'Update your VS Code GitHub Copilot extension and sign in with your GitHub account to activate free access.',
      key_points: [
        '2,000 monthly code completions included at $0 cost',
        '50 multi-turn AI chat messages per month powered by top frontier models',
        'No credit card or student verification needed—open to all developers'
      ]
    },
    importance_score: 94,
    relevance_score: 95,
    is_featured: false,
    is_trending: true,
    published_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'news_03',
    title: 'Cloudflare Announces Zero-Latency D1 Database Replication Worldwide',
    description: 'Cloudflare D1 serverless SQL database now automatically replicates read replicas to over 300 global edge locations at zero additional charge.',
    content: 'Cloudflare rolled out automated read replication for D1, its serverless SQLite database. Queries from any location around the world now resolve within 15ms by reading directly from the nearest Cloudflare point of presence.',
    url: 'https://blog.cloudflare.com/d1-global-read-replication/',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    source_name: 'Cloudflare Blog',
    category: 'cloud',
    tags: ['Cloudflare', 'D1', 'Serverless', 'SQLite', 'Edge'],
    read_time_minutes: 3,
    summary: {
      what: 'Cloudflare enabled automatic global edge read replication for D1 serverless database.',
      why: 'Enables developers to build lightning-fast web applications without paying for distributed database clusters.',
      action: 'Enable replication in your wrangler.toml file or Cloudflare dashboard with a single configuration flag.',
      key_points: [
        'Global read latency drops under 15ms worldwide',
        'Zero added cost on free tier up to 5M monthly read rows',
        'Automatic transaction routing to primary region for ACID writes'
      ]
    },
    importance_score: 88,
    relevance_score: 91,
    is_featured: false,
    is_trending: false,
    published_at: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
  },
  {
    id: 'news_04',
    title: 'React 19.2 Released with Native Server Action Optimistic UI Hooks',
    description: 'The React team has published React 19.2, introducing built-in optimistic state management and zero-bundle server component streaming enhancements.',
    content: 'React 19.2 brings major refinements to Server Actions, improving `useOptimistic` reliability, fine-grained hydration prioritization, and built-in transitions for async forms.',
    url: 'https://react.dev/blog/2026/react-19-2',
    image_url: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=1200&q=80',
    source_name: 'React Official',
    category: 'development',
    tags: ['React', 'Next.js', 'Frontend', 'JavaScript'],
    read_time_minutes: 3,
    summary: {
      what: 'React 19.2 released with polished optimistic hooks and enhanced server action streaming.',
      why: 'Significantly simplifies client-side state synchronization for modern full-stack web applications.',
      action: 'Run `npm install react@latest react-dom@latest` to upgrade existing React 19 projects.',
      key_points: [
        'Smoother transitions when handling async server actions',
        'Enhanced useOptimistic hook with rollback support',
        'Better hydration error recovery without full page reloads'
      ]
    },
    importance_score: 82,
    relevance_score: 89,
    is_featured: false,
    is_trending: false,
    published_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'news_05',
    title: 'Meta Open-Sources Llama 3.3 70B: Frontier Intelligence on Single GPU',
    description: 'Meta released Llama 3.3 70B, providing performance on par with the original 405B model while running comfortably on consumer/budget hardware.',
    content: 'Meta AI unveiled Llama 3.3 70B under an open community license. Thanks to aggressive knowledge distillation and architecture optimizations, it matches Llama 3.1 405B performance on math, coding, and multilingual benchmarks.',
    url: 'https://ai.meta.com/blog/llama-3-3-open-source/',
    image_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80',
    source_name: 'TechCrunch',
    category: 'open_source',
    tags: ['Llama', 'Meta', 'OpenSource', 'LocalAI', 'Ollama'],
    read_time_minutes: 5,
    summary: {
      what: 'Meta open-sourced Llama 3.3 70B with 405B-level reasoning capabilities.',
      why: 'Allows independent developers to host frontier-tier AI locally or on low-cost cloud GPUs without paying API subscriptions.',
      action: 'Pull the model immediately via `ollama run llama3.3` or download weights from Hugging Face.',
      key_points: [
        'Matches 405B benchmarks at a fraction of compute cost',
        'Runs with 4-bit quantization on a single 24GB VRAM GPU',
        'Commercially usable open license for up to 700M monthly users'
      ]
    },
    importance_score: 92,
    relevance_score: 94,
    is_featured: false,
    is_trending: true,
    published_at: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
  }
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp_01',
    title: 'Google Cloud $300 Credits + Free Gemini 2.0 Flash Pro Access',
    provider: 'Google Cloud',
    provider_logo: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Google_Cloud_logo.svg',
    description: 'Get $300 in free Google Cloud credits valid across Compute Engine, BigQuery, Vertex AI, and Cloud Run, plus 15 free RPM on Gemini 2.0 Pro.',
    opportunity_type: 'cloud',
    category: 'cloud',
    normal_value: '$300.00',
    current_value: 'FREE',
    eligibility: 'New & Existing Google Accounts',
    claim_url: 'https://cloud.google.com/free',
    official_url: 'https://cloud.google.com/free',
    requirements: 'Valid Google Account + debit/credit card for verification ($0 charge)',
    expiry_date: new Date(Date.now() + 15 * 24 * 3600 * 1000).toISOString(),
    is_expiring_soon: false,
    status: 'ACTIVE',
    verification_status: 'VERIFIED',
    last_verified_at: new Date().toISOString(),
    importance_score: 98,
    relevance_score: 99,
    priority: 'Critical',
    why_care: 'Crucial for hosting full-stack applications, running BigQuery experiments, and accessing cutting-edge Gemini models without paying out of pocket.',
  },
  {
    id: 'opp_02',
    title: 'Microsoft Azure AI Certification Voucher (100% Fee Waiver)',
    provider: 'Microsoft Learn',
    provider_logo: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg',
    description: 'Complete the Microsoft Cloud Skills Challenge to receive a 100% free exam voucher for AI-900 (Azure AI Fundamentals) or DP-900.',
    opportunity_type: 'certification',
    category: 'education',
    normal_value: '$99.00',
    current_value: '100% OFF',
    eligibility: 'Students & Developers Worldwide',
    claim_url: 'https://learn.microsoft.com/en-us/credentials/certifications/',
    official_url: 'https://learn.microsoft.com',
    requirements: 'Complete 5 learning modules before August 20',
    coupon_code: 'AUTO-CLAIMED',
    expiry_date: new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString(),
    is_expiring_soon: true,
    status: 'EXPIRING_SOON',
    verification_status: 'VERIFIED',
    last_verified_at: new Date().toISOString(),
    importance_score: 97,
    relevance_score: 96,
    priority: 'Critical',
    why_care: 'Official Microsoft industry certification exam voucher normally priced at $99. Valid for official Pearson VUE proctored exam.',
  },
  {
    id: 'opp_03',
    title: 'GitHub Student Developer Pack ($200k+ Free Dev Tools)',
    provider: 'GitHub Education',
    provider_logo: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
    description: 'Access 100+ premium developer tools for free including JetBrains IDEs, DigitalOcean $200 credits, GitHub Copilot Pro, Canva Pro, Namecheap free domain.',
    opportunity_type: 'software',
    category: 'education',
    normal_value: '$200,000+ Value',
    current_value: '100% FREE',
    eligibility: 'Any Verified Student (.edu or School ID)',
    claim_url: 'https://education.github.com/pack',
    official_url: 'https://education.github.com/pack',
    requirements: 'Student email (.edu) or valid school student ID card',
    expiry_date: undefined,
    is_expiring_soon: false,
    status: 'ACTIVE',
    verification_status: 'VERIFIED',
    last_verified_at: new Date().toISOString(),
    importance_score: 99,
    relevance_score: 98,
    priority: 'High',
    why_care: 'The gold standard student developer bundle. Provides free access to virtually every essential developer tool and cloud provider.',
  },
  {
    id: 'opp_04',
    title: 'Groq Cloud Ultra-Fast Llama 3 Inference (14,400 Free Tokens/Min)',
    provider: 'Groq',
    provider_logo: 'https://groq.com/favicon.ico',
    description: 'Get free permanent developer tier API access to Groq LPU inference delivering over 500 tokens/second on Llama 3.3 and Mixtral.',
    opportunity_type: 'ai_credits',
    category: 'ai',
    normal_value: '$25/month Value',
    current_value: 'FREE FOREVER',
    eligibility: 'All Developers',
    claim_url: 'https://console.groq.com/',
    official_url: 'https://groq.com/',
    requirements: 'Free account sign up with GitHub or Google',
    expiry_date: undefined,
    is_expiring_soon: false,
    status: 'ACTIVE',
    verification_status: 'VERIFIED',
    last_verified_at: new Date().toISOString(),
    importance_score: 91,
    relevance_score: 94,
    priority: 'High',
    why_care: 'Blazing fast sub-second AI inference that powers real-time voice agents, coding assistants, and summarization pipelines for $0.',
  },
  {
    id: 'opp_05',
    title: 'AWS Community Builders Summer Hackathon ($50,000 Prize Pool)',
    provider: 'Amazon Web Services',
    provider_logo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg',
    description: 'Build serverless & generative AI apps on AWS. All approved participants receive $100 AWS activate credits instantly upon submitting a project concept.',
    opportunity_type: 'competition',
    category: 'career',
    normal_value: '$100 Instant Credits',
    current_value: 'FREE ENTRY',
    eligibility: 'Developers 18+ Globally',
    claim_url: 'https://aws.amazon.com/events/hackathons/',
    official_url: 'https://aws.amazon.com',
    requirements: 'Submit project idea on Devpost/AWS portal before deadline',
    expiry_date: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(),
    is_expiring_soon: true,
    status: 'EXPIRING_SOON',
    verification_status: 'VERIFIED',
    last_verified_at: new Date().toISOString(),
    importance_score: 95,
    relevance_score: 92,
    priority: 'Critical',
    why_care: 'Instant $100 AWS credits just for participating, plus high-visibility prize money and potential hiring interviews from AWS partners.',
  },
  {
    id: 'opp_06',
    title: 'MongoDB Atlas Serverless 512MB Cluster + Vector Search',
    provider: 'MongoDB',
    provider_logo: 'https://www.mongodb.com/assets/images/global/favicon.ico',
    description: 'Free forever M0 cluster with 512MB storage, shared RAM, automated backups, and built-in vector search for AI embeddings.',
    opportunity_type: 'software',
    category: 'cloud',
    normal_value: '$15/mo Value',
    current_value: 'FREE FOREVER',
    eligibility: 'All Developers',
    claim_url: 'https://www.mongodb.com/cloud/atlas/register',
    official_url: 'https://www.mongodb.com/cloud/atlas',
    requirements: 'Free account sign up',
    expiry_date: undefined,
    is_expiring_soon: false,
    status: 'ACTIVE',
    verification_status: 'VERIFIED',
    last_verified_at: new Date().toISOString(),
    importance_score: 84,
    relevance_score: 87,
    priority: 'Medium',
    why_care: 'Ideal lightweight document database with native vector similarity search for prototyping RAG and full-stack applications.',
  }
];

export const INITIAL_REPORT: DailyReport = {
  id: 'rep_2026_08_16',
  date: '2026-08-16',
  title: 'Tech Sentinel Daily Intelligence',
  headline: 'Claude 3.7 Hybrid Reasoning Arrives, GitHub Makes Copilot Free, and $400 in Cloud Credits Available',
  thirty_sec_summary: 'Anthropic introduced Claude 3.7 with breakthrough hybrid reasoning; GitHub dropped Copilot pricing to $0 for all VS Code users; Microsoft and AWS released limited-time certification vouchers and $100 instant credits expiring within 48 hours.',
  top_stories: [
    { id: 'news_01', title: 'Anthropic Launches Claude 3.7 Sonnet with Hybrid Reasoning Mode', score: 96, summary: 'Breakthrough hybrid reasoning with dynamic thinking tokens.' },
    { id: 'news_02', title: 'GitHub Releases Copilot Free for All Visual Studio Code Users', score: 94, summary: '2,000 completions/mo at $0 cost for all VS Code developers.' },
    { id: 'news_05', title: 'Meta Open-Sources Llama 3.3 70B: Frontier Intelligence on Single GPU', score: 92, summary: 'Matches 405B capabilities running locally on a single GPU.' }
  ],
  free_opportunities: [
    { id: 'opp_01', title: 'Google Cloud $300 Credits + Free Gemini 2.0 Flash Pro Access', value: '$300', provider: 'Google Cloud', claim_url: 'https://cloud.google.com/free' },
    { id: 'opp_02', title: 'Microsoft Azure AI Certification Voucher (100% Fee Waiver)', value: '$99', provider: 'Microsoft Learn', claim_url: 'https://learn.microsoft.com' },
    { id: 'opp_04', title: 'Groq Cloud Ultra-Fast Llama 3 Inference', value: 'FREE FOREVER', provider: 'Groq', claim_url: 'https://console.groq.com/' }
  ],
  student_opportunities: [
    { id: 'opp_03', title: 'GitHub Student Developer Pack ($200k+ Free Dev Tools)', value: '$200,000+' }
  ],
  open_source_highlights: [
    { title: 'Llama 3.3 70B Weights on Hugging Face', category: 'ai' },
    { title: 'Cloudflare D1 Global Replication', category: 'cloud' }
  ],
  expiring_soon: [
    { id: 'opp_05', title: 'AWS Summer Hackathon ($100 Credits)', expires_in: '2 days' },
    { id: 'opp_02', title: 'Microsoft Azure AI Certification Voucher', expires_in: '3 days' }
  ],
  sentinel_take: 'Today’s developer landscape took a massive leap in accessibility. With Copilot becoming free and frontier reasoning models like Claude 3.7 and Llama 3.3 readily accessible, developers can build complex AI systems without subscription overhead. Do not miss the Microsoft AI cert voucher expiring on August 20.',
  stats: {
    total_scanned: 142,
    new_news: 18,
    new_opportunities: 6,
    verified_active: 24,
    expiring_count: 2
  },
  published_at: new Date().toISOString()
};

export const INITIAL_PREFERENCES: UserPreferences = {
  id: 'default',
  user_name: 'Balaji',
  theme: 'system',
  categories: ['ai', 'cloud', 'development', 'open_source', 'cybersecurity', 'startups'],
  keywords: ['react', 'llm', 'credits', 'internship', 'certification', 'hackathon', 'copilot'],
  opportunity_types: ['software', 'ai_credits', 'cloud', 'education', 'certification', 'competition', 'career'],
  enable_daily_brief: true,
  enable_critical_alerts: true,
  ai_provider: 'fallback'
};

export const INITIAL_AGENT_STATS: AgentStats = {
  status: 'ACTIVE',
  last_scan_time: '4 mins ago',
  sources_checked: 128,
  new_opportunities_today: 6,
  next_report_time: '9:00 PM',
  system_cost: '₹0.00'
};
